### ISSUE TITLE
sendNewEmail 

### ISSUE THREAD

**Issue by ConnorSimply** [team-plain/typescript-sdk#39]
Heyo, I am using the sendNewEmail function to send an email to the customer once they have completed a contact us form and I am getting some weird error-handling behaviors.

This is my code that I am using...
```js
const customerEmailRes = await client.sendNewEmail({
    customerId: upsertCustomerRes.data.customer.id,
    textContent: `We will be with you shortly.`,
    subject: "Thank you for contacting us"
});
```
and I am getting this as the response, **HOWEVER**, it still succeeds in sending the email?
```json
{
  type: 'unknown',
  message: 'Unknown error',
  err: Error: Unexpected response received
      at request (/Users/user/Documents/GitHub/website/node_modules/@team-plain/typescript-sdk/dist/index.js:186:13)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PlainClient.sendNewEmail (/Users/user/Documents/GitHub/website/node_modules/@team-plain/typescript-sdk/dist/index.js:394:17)
      at async handler (webpack-internal:///(api)/./pages/api/contact-form.ts:83:30)
}
```

**Comment by mattvagni** [comment]
Hey @ConnorSimply sorry for the late follow-up here! 

Is this still happening? If so can you please email us your workspace id so we can investigate this on our side? Your code is definitely correct, so this is something on our side.

Alternatively, if you update to the latest version you will also receive a request ID in the error which can help us debug this.

Thanks
